openapi: 3.0.3
info:
  title: Betting API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Development server
tags:
  - name: betting
paths:
  /ping:
    get:
      operationId: ping
      tags:
        - betting
      responses:
        200:
          description: OK
#  components:
#    schemas:

